### ISSUE TITLE
edit label texts in the mainframe panel.

### ISSUE THREAD

**Issue by dragonyanglong** [dragonyanglong/diffpy.pdfgui#26]

**Comment by dragonyanglong** [comment]
The mainframe.py doesn't have corresponding .wxg file

**Comment by dragonyanglong** [comment]
Hi @pavoljuhas, can I ask a question about the wxGlade gui design part. Usually, we use wxGlade to design gui and automatically generate the wxpython code. However, I found some parts of gui do not have wxGlade `wxg` file. 

For example, I would like to change some texts in the mainframe panel, the `PDFfit2 output` text, which I think is in https://github.com/diffpy/diffpy.pdfgui/blob/master/src/diffpy/pdfgui/gui/mainframe.py/#L353. But there is no corresponding `mainframe.wxg` file in the `gui/design` folder. I tried to directly change the `PDFfit2 output` text into some other texts in the `mainframe.py`, but it doesn't seem working. How to deal with it?

And there are more `.py` files in the `gui` folder than `.wxg` files in the `gui/design` folder.

Thank you!
Long

**Comment by pavoljuhas** [comment]
Hi @dragonyanglong - it seems mainframe.py needs to be changed directly - see [this comment](
https://github.com/diffpy/diffpy.pdfgui/blob/ff1af6fbd8fcc8e9908e6cf41c93b2a7b04d0313/src/diffpy/pdfgui/gui/mainframe.py#L59-L60) and 2e91ceb79ae474a4b5d1ceb5c0c147370950a353.  A good way to quickly check if any wxg files were removed is
 
```sh
$ git log --diff-filter=D --name-status \*.wxg 
...
commit 2e91ceb79ae474a4b5d1ceb5c0c147370950a353
Author: Christopher Farrow <farrowch@gmail.com>
Date:   Fri Mar 23 21:53:17 2007 +0000

    Changed the name of mainpanel.py to mainframe.py to better reflect its purpose.
    Implemented window docking menu item. Removed server configuration menu item.
    mainframe.py is no longer editable with wxglade, so the project file was
    deleted.

D       pdfgui/gui/design/mainpanel.wxg
```

> And there are more .py files in the gui folder than .wxg files in the gui/design folder.

Those were most likely written without wxglade.  To be sure, I would look for any `# begin wxGlade`, `# end wxGlade` markers in the source.  If they are present and the `wxg` file is missing, I would check `git log --name-status \*.wxg` to find out when/why did the wxg file disappear.

**Comment by dragonyanglong** [comment]
Thanks Pavol. Fixed the problem.
